/**
 * Long-form service page content.
 *
 * Generated by an agent pipeline that drafted each page from the real `services`
 * and `projects` records, then put every draft through an adversarial
 * fact-checker. 35 unsupported claims (invented metrics, timelines, client
 * details) were flagged and removed before this was written.
 *
 * Kept in code rather than the database deliberately: it is version-controlled,
 * reviewable in a diff, and server-rendered, so crawlers and AI engines (which do
 * not execute JavaScript) read it from the initial HTML. The admin dashboard
 * still owns title / desc_text / features.
 *
 * Every factual claim here traces to real project data. Do not add metrics,
 * timelines, testimonials or client names that are not in Supabase.
 */
export type ServiceContent = {
  service_id: number;
  title: string;
  meta_description: string;
  hero_answer: string;
  sections: { heading: string; body: string }[];
  deliverables: string[];
  faq: { q: string; a: string }[];
  word_count: number;
};

export const SERVICE_CONTENT: Record<number, ServiceContent> = {
  "1": {
    "service_id": 1,
    "title": "Mobile Innovation: Cross-Platform iOS & Android App Development",
    "meta_description": "iOS and Android apps built in React Native or Flutter, with secure API integrations, smooth performance and App Store and Play Store deployment support.",
    "hero_answer": "Mobile Innovation is DevoraX's cross-platform mobile app service: we build fast, scalable and visually polished applications in React Native or Flutter that run on iOS and Android from one codebase, with optimized performance and smooth animations, secure API integrations, and App Store and Play Store deployment support.",
    "sections": [
      {
        "heading": "What does a cross-platform mobile app build include?",
        "body": "A cross-platform build means one codebase produces both an iOS app and an Android app, instead of two separate native teams maintaining two separate products. The work covers the app on both platforms, the interface and animation layer that makes it feel native, secure integrations with your APIs and third-party services, performance tuning, and App Store and Play Store deployment support.\n\nScope is agreed before code is written, so you know which screens, user roles and integrations belong to the first release and which are deliberately held back.\n\nThe commercial logic is simple. One codebase is one set of features to build, test and maintain, so a fixed bug or a redesigned screen ships to both platforms at once rather than being implemented twice. The FinTech Mobile App is the clearest example in our work: a cross-platform React Native app with a Node.js backend, handling high daily transaction volumes across platforms."
      },
      {
        "heading": "Who is this mobile app development service for?",
        "body": "This service is for teams that need a real product in users' hands, not a prototype. The linked work spans three very different buyers, which is a fair map of who it suits.\n\nThe first is banking and transaction-heavy products, where reliability and security decide whether people trust the app at all. The FinTech Mobile App was built for exactly that pressure: traditional banking apps struggling with scalability, transaction reliability and security while handling high daily transaction volumes across platforms.\n\nThe second is subscription and service businesses. Bondly Pet Care Platform came from pet care services struggling to manage subscriptions, credits, payments and notifications efficiently.\n\nThe third is marketplaces that live or die on fresh data. AgroBridge answered agricultural marketplaces needing real-time data sync and mobile-first user experiences. If your product looks like one of those three, this service is aimed at you."
      },
      {
        "heading": "How does the mobile app development process work?",
        "body": "The process runs in stages, and each stage produces something you can review rather than a status update. It starts with discovery: user roles, core flows, integrations and the definition of the first release.\n\nArchitecture comes next. The app structure, the API contract and the data model are settled before feature work begins, because retrofitting an architecture around finished screens is where mobile projects lose time. Where an app handles payments or real-time data, the security model carries most of that risk, so it is agreed with you rather than assumed.\n\nBuild and review then alternate. Features are delivered in working increments and tested as installable builds on real devices, so feedback is given on the running app rather than on screenshots.\n\nThe final stage is release: a performance and animation pass across both platforms, then App Store and Play Store deployment support."
      },
      {
        "heading": "Which technologies do you use to build mobile apps?",
        "body": "The front end is React Native or Flutter, chosen per project rather than by default. Both mobile builds linked to this service, the FinTech Mobile App and AgroBridge, were delivered in React Native, so that is where the deepest evidence sits. Flutter is offered for teams whose existing stack or design requirements point that way.\n\nBehind the app, past projects used what the problem needed. The FinTech Mobile App runs on a Node.js backend with secure APIs and real-time transaction handling. AgroBridge is a React Native and Firebase platform with real-time synchronization and file uploads, using cloud storage.\n\nCommercial features are wired to proven services rather than rebuilt. Bondly Pet Care Platform combines Node.js and Firebase with Stripe for payments, OneSignal for notifications and AWS deployment.\n\nWhat this service itself covers is the app and its secure API integrations. If you already run a backend, the app is built against it."
      },
      {
        "heading": "Can a cross-platform app handle high transaction volume and security?",
        "body": "Yes, and there is a build to point at. Traditional banking apps struggled with scalability, transaction reliability and security while handling high daily transaction volumes across platforms. That was the stated problem behind the FinTech Mobile App.\n\nWhat was built was a cross-platform React Native app with a Node.js backend, implementing secure APIs, real-time transaction handling and bank-grade security standards.\n\nThe client reports 99.9% uptime while successfully processing 50k+ daily transactions, with improved performance and user trust. Cross-platform delivery and reliability were not traded against each other.\n\nThe practical takeaway for your project is that the constraint is rarely the framework. It is how authentication, API security, error handling and real-time state are handled. Those are the decisions worth settling with you while the architecture is being agreed, rather than after screens are built."
      },
      {
        "heading": "How do you keep a cross-platform app fast on both iOS and Android?",
        "body": "Optimized performance and smooth animations are treated as build work, not a final coat of polish. A single codebase removes duplicated feature work, but it does not excuse an app that stutters on one platform and not the other.\n\nIn practice that means checking the things users actually feel: list and image rendering, navigation transitions, animation smoothness and startup behaviour, exercised on real iOS and Android devices rather than on simulators alone. Both platforms are reviewed, because a build that only ever gets tested on the developer's phone is a build that only works on that phone.\n\nThe goal is an app that feels native on each platform despite sharing a codebase. That is the same quality bar behind the FinTech Mobile App's improved performance and AgroBridge's improved mobile usability, and it is why a dedicated performance and animation pass sits in the schedule before release."
      },
      {
        "heading": "What results have past mobile projects delivered?",
        "body": "Three linked projects show the range, and they are not all the same kind of build.\n\nThe FinTech Mobile App is a cross-platform React Native app with a Node.js backend, and the client reports 99.9% uptime while successfully processing 50k+ daily transactions under bank-grade security standards, with improved performance and user trust. It is the one project here with hard numbers attached.\n\nBondly Pet Care Platform solved a different problem: pet care services could not manage subscriptions, credits, payments and notifications efficiently. The Node.js and Firebase platform, with Stripe payments, AWS deployment and notification services, delivered a scalable subscription-based pet care ecosystem with automated billing and real-time engagement. It is live at bondlypets.com.\n\nAgroBridge, a React Native and Firebase mobile platform with real-time synchronization and file uploads, improved marketplace efficiency, real-time interactions and mobile usability. Those outcomes are described qualitatively; no figures are claimed for them."
      }
    ],
    "deliverables": [
      "A cross-platform mobile app running on iOS and Android from a single React Native or Flutter codebase",
      "Secure API integrations with your services and third-party providers",
      "Payment, notification and cloud data integrations where the product needs them (for example Stripe, OneSignal or Firebase)",
      "An agreed first-release scope covering screens, user roles and integrations, settled before build starts",
      "Working builds installed and reviewed on real devices as features are completed",
      "A performance and animation pass across iOS and Android before release",
      "App Store and Play Store deployment support"
    ],
    "faq": [
      {
        "q": "Should I choose React Native or Flutter for my app?",
        "a": "Both are offered, and the choice follows your existing stack, your team's skills and the integrations you need. The two mobile projects linked to this service, the FinTech Mobile App and AgroBridge, were both delivered in React Native, so that path carries the most demonstrated work. The decision is made in discovery, before any code is written."
      },
      {
        "q": "Can a cross-platform app be secure enough for financial transactions?",
        "a": "The FinTech Mobile App is the example: a cross-platform React Native app with a Node.js backend, secure APIs, real-time transaction handling and bank-grade security standards, with a client-reported 99.9% uptime while processing 50k+ daily transactions. Security comes from how authentication, APIs and state handling are designed, which is why those choices are agreed with you rather than assumed."
      },
      {
        "q": "Can you connect the app to my existing backend, payment provider and notification service?",
        "a": "Yes. Secure API integration is one of the five things this service covers, and the linked projects show it in practice: Node.js backends, Firebase for real-time synchronization, file uploads and cloud storage, Stripe for payments, and OneSignal for notifications. If you already run a backend, the app is built against it rather than replacing it."
      },
      {
        "q": "Do you help get the app into the App Store and Play Store?",
        "a": "Yes. App Store and Play Store deployment support is part of the service, so releasing the app is inside the engagement rather than left to you once the build is finished. What that support involves for your specific product is agreed when scope is set, since the two stores have different requirements and final approval always sits with the store rather than with us."
      },
      {
        "q": "Is there a live product I can look at before hiring you?",
        "a": "Yes. Bondly Pet Care Platform, the subscription-based pet care ecosystem built with Node.js and Firebase with Stripe payments, AWS deployment and notification services, is live at bondlypets.com. No public link is listed for the FinTech Mobile App or AgroBridge, but both can be walked through as case studies covering the problem, the stack used and the outcome recorded for each."
      }
    ],
    "word_count": 1058
  },
  "2": {
    "service_id": 2,
    "title": "AI & Full-Stack Web Development | DevoraX",
    "meta_description": "Next.js and React front ends, Python and FastAPI services, and AI built into the stack, from architecture and API design through to containerized deployment.",
    "hero_answer": "AI and full-stack web development is the end-to-end build of a web application: interface, API layer, data model, and infrastructure, with AI integrated into the product rather than bolted on afterwards. DevoraX delivers these as Next.js and modern React front ends backed by Python services, REST and GraphQL APIs, and secure authentication.",
    "sections": [
      {
        "heading": "What is AI and full-stack web development?",
        "body": "Full-stack web development means one team owns every layer of an application: the React interface a user sees, the API that serves it, the data model underneath, and the infrastructure it runs on. Adding AI to that stack means the intelligence lives inside those same layers rather than in a separate tool.\n\nIn practice that can be a recommendation system that ranks what each user sees, a model that processes an uploaded image, or a machine learning service exposed through an API the front end already calls.\n\nThe distinction matters because AI features usually fail at the seams. A model that works in a notebook still needs an endpoint, authentication, error handling, and an interface that behaves sensibly when inference is slow.\n\nDevoraX builds both halves together: Next.js and modern React architecture at the front, scalable backend architecture behind it, connected by REST and GraphQL APIs and fronted by secure authentication systems."
      },
      {
        "heading": "Who is this service for?",
        "body": "This service fits teams that need a production web application rather than a prototype. The delivered work behind it covers two shapes of build: a multi-vendor eCommerce marketplace and an AI image stylization platform, both built as complete applications rather than experiments.\n\nIt suits you if you have a model or a workflow that already works in isolation and now needs to be wrapped in a usable, authenticated, deployable product. It also suits a product whose front end, API, AI layer, and deployment path are better owned by one team than split across several.\n\nIt is probably not the right fit for a brochure site, a one-page template, or a static landing page, because that work does not need this architecture and the cost would not be justified by it.\n\nEngagements start with a scoped discovery conversation, so the architecture is agreed before production code is written."
      },
      {
        "heading": "How does the delivery process work?",
        "body": "Delivery runs in four stages. Discovery maps the product requirements, the data you already hold, and the constraint that actually decides the architecture, whether that is scale, latency, or security.\n\nArchitecture then fixes the decisions that are expensive to reverse: how the backend is split into services, REST or GraphQL, where authentication lives, and how the application is containerized for deployment.\n\nBuild happens in reviewable increments. Front-end and backend work run in parallel against an agreed API contract, so the interface is not waiting on the data layer and the data layer is not guessing what the interface needs. AI components sit behind the same API boundary as everything else, which means a model can be swapped or retrained without a front-end rewrite.\n\nHardening closes the project: authentication tested, containers built, and the deployment path exercised before the application goes in front of real users."
      },
      {
        "heading": "Which technologies are used to build these applications?",
        "body": "Front ends are built on Next.js and modern React architecture, which gives server rendering for pages that need to be indexed and client-side interactivity where the product needs it.\n\nBackend work is Python-based where AI is involved. On the AI Art Stylization Platform, FastAPI served Stable Diffusion and SAM with real-time processing, which is the pattern used whenever inference has to happen behind a web request rather than in an overnight batch job.\n\nData moves over REST and GraphQL APIs, with secure authentication systems sitting in front of them rather than scattered across individual endpoints.\n\nFor deployment, services can be containerized with Docker and orchestrated with Kubernetes. The AI E-Commerce Ecosystem was built as a containerized microservices architecture using Next.js, Docker, and Kubernetes.\n\nStack choices follow the requirement rather than habit. A single-service application does not get Kubernetes because a marketplace once needed it."
      },
      {
        "heading": "What AI capabilities can be built into a web application?",
        "body": "Two patterns cover the AI work behind this service. The first is recommendation and personalization. On the AI E-Commerce Ecosystem, the problem was that multi-vendor eCommerce platforms faced performance bottlenecks, poor scalability, and a lack of personalized shopping experiences, so an AI-driven recommendation system was designed into a containerized microservices architecture on Next.js, Docker, and Kubernetes.\n\nThe second is generative and vision work served in real time. The AI Art Stylization Platform answered image stylization tools that lacked precise control and real-time AI performance, combining FastAPI, Stable Diffusion, and SAM into segmentation-based stylization, so a user could stylize a specific segmented region rather than the whole image.\n\nBoth patterns share the same engineering requirements: an inference endpoint that works under production conditions, sensible behaviour when a model is slow or unavailable, and a front end that communicates progress instead of freezing.\n\nIf a requirement does not need a model, it gets built without one."
      },
      {
        "heading": "What proof is there that this approach works?",
        "body": "Two delivered projects sit behind this service. On the AI E-Commerce Ecosystem, the stated problem was that multi-vendor eCommerce platforms faced performance bottlenecks, poor scalability, and a lack of personalized shopping experiences. The build was a containerized microservices architecture using Next.js, Docker, and Kubernetes with AI-driven recommendation systems, and the recorded result was a highly scalable marketplace with personalized shopping experiences and vendor management.\n\nThe AI Art Stylization Platform started from image stylization tools that lacked precise control and real-time AI performance. FastAPI, Stable Diffusion, and SAM were combined into segmentation-based stylization, and the recorded result was real-time AI image stylization with high-quality outputs and precise region control.\n\nNeither project carries a public live link in the portfolio, so the proof here is the architecture and the recorded outcomes above, not a demo URL. No traffic, uptime, or revenue figures are published for either build, and none are claimed on this page."
      },
      {
        "heading": "How is the application kept secure and scalable as it grows?",
        "body": "Security and scale are decided by architecture, not added at the end. Authentication is built as a system rather than a per-page check: sessions or tokens issued in one place, checks applied at the API boundary, and secrets kept out of the client bundle.\n\nScalability comes from separating the parts of an application that grow at different rates, which is the reasoning behind a microservices split. The AI E-Commerce Ecosystem was designed that way, as a containerized microservices architecture using Next.js, Docker, and Kubernetes, against a brief where poor scalability was the stated problem.\n\nDocker gives every service the same environment locally, in staging, and in production, which removes the class of bug that only appears after deployment. Kubernetes handles scheduling and restarts once there is more than one service to run.\n\nSmaller products get a simpler version of this, but the principle holds: no secrets in the browser, no single process doing everything."
      }
    ],
    "deliverables": [
      "Production front end built on Next.js and modern React architecture",
      "Backend services built as a scalable backend architecture",
      "REST or GraphQL API layer connecting the interface to those services",
      "AI or ML integration served behind its own API endpoint, where the scope includes one",
      "Python inference service, following the FastAPI pattern used on the AI Art Stylization Platform",
      "Secure authentication system covering sign-in and session handling",
      "Dockerized services, plus Kubernetes orchestration where the architecture calls for it",
      "A deployed, running application rather than a local prototype build"
    ],
    "faq": [
      {
        "q": "Do you build AI models from scratch or integrate existing ones?",
        "a": "The delivered work behind this service integrates existing models and engineers the application around them. The AI Art Stylization Platform served Stable Diffusion and SAM through a FastAPI backend, and the AI E-Commerce Ecosystem had an AI-driven recommendation system designed into its microservices architecture. There is no from-scratch model training project in the portfolio, so integration is what the evidence here supports. Which route your product needs is settled in discovery."
      },
      {
        "q": "Can you work with an existing codebase, or does it have to be a new build?",
        "a": "Both projects linked to this service, the AI E-Commerce Ecosystem and the AI Art Stylization Platform, were new builds, so that is where the documented proof sits. For an existing application, discovery starts with a review of the current repository, data model, API surface, and deployment setup, and that review is what decides whether extending what exists, replacing one layer, or rebuilding is sensible. No recommendation is made before that assessment."
      },
      {
        "q": "What if we are not sure we actually need AI?",
        "a": "That is a discovery question, not a sales question. If a rules-based feature, better search, or a cleaner data model solves the problem, that is what gets built, because it is cheaper to run and easier to maintain. AI is used where ranking, generation, or perception is genuinely the requirement, as it was for recommendations on the AI E-Commerce Ecosystem and segmentation-based stylization on the AI Art Stylization Platform."
      },
      {
        "q": "Will the architecture scale, or will we need a rewrite later?",
        "a": "Scalable backend architecture is one of the core parts of this service, and the shape of it is chosen in the architecture stage against your expected load rather than applied by default. The AI E-Commerce Ecosystem was built as a containerized microservices architecture on Next.js, Docker, and Kubernetes, and the recorded result was a highly scalable marketplace. A smaller product gets a simpler structure, because unnecessary services cost more to run and maintain than they save."
      },
      {
        "q": "Which front-end framework will our application be built on?",
        "a": "Next.js with modern React architecture is the default, which gives server rendering for pages that need to be indexed and client-side interactivity for the parts of the product that are genuinely interactive. It is also the front end used on the AI E-Commerce Ecosystem. The final choice is confirmed during the architecture stage, based on your indexing needs, expected traffic pattern, and how the AI layer is consumed."
      }
    ],
    "word_count": 1101
  },
  "3": {
    "service_id": 3,
    "title": "Cloud Architecture Services | AWS, Docker & Kubernetes | DevoraX",
    "meta_description": "Design and build of AWS cloud infrastructure: serverless or containerized workloads, CI/CD pipelines, high availability, monitoring and cost control.",
    "hero_answer": "Cloud architecture is the design and build of the infrastructure your software runs on: AWS cloud infrastructure, Docker and Kubernetes orchestration, CI/CD pipeline setup, high availability and monitoring, and cost optimization strategies. DevoraX builds robust cloud infrastructures for high availability, scalability, and security using industry-proven DevOps practices. Workloads run serverless, containerized, or a mix of both.",
    "sections": [
      {
        "heading": "What is cloud architecture as a service?",
        "body": "Cloud architecture is the layer between your product and the servers that actually run it. A cloud architecture engagement covers AWS cloud infrastructure, Docker and Kubernetes orchestration, CI/CD pipeline setup, high availability and monitoring, and cost optimization strategies.\n\nIn practice that means deciding how your application is packaged, where it is deployed, how new code reaches production, and what happens when traffic spikes or a component fails. The goal is infrastructure that scales with demand rather than infrastructure that has to be rebuilt every time the product grows.\n\nThis is not a one-size template. A serverless backend built on AWS Lambda functions suits an event-driven product, while a containerized workload orchestrated with Kubernetes suits services that need long-running processes and fine-grained control over the runtime. We choose the shape that fits your workload, then make deployment repeatable so releases stop being a manual, risky event for your engineering team."
      },
      {
        "heading": "Who needs a cloud architecture partner?",
        "body": "Cloud architecture work is for teams whose infrastructure has become the bottleneck rather than the product. That usually looks like one of three situations.\n\nThe first is a new product that needs a backend designed for the load it will actually carry. Food Magnet: Vender is an example: a Flutter mobile app and a React admin dashboard on a serverless AWS backend, with live food truck location tracking as part of the build.\n\nThe second is an existing application that works but deploys slowly, breaks under load, or costs more each month than anyone can explain. The third is a team with no dedicated DevOps engineer, where developers spend their time babysitting servers instead of shipping features. If deployments require one specific person to be online, or nobody can say what happens when an instance dies, this is the work that fixes it."
      },
      {
        "heading": "How does a cloud architecture project get delivered?",
        "body": "Delivery starts with an assessment of what you already have: current hosting, deployment steps, traffic patterns, data stores, and the failure points your team already knows about. Nothing moves before that picture is clear.\n\nNext comes architecture design. We map the target AWS environment, choose between serverless functions, containers, or a mix, and define how services, storage, databases, and third-party integrations such as payments or notifications connect to each other.\n\nBuild follows. Infrastructure is provisioned on AWS, applications are containerized with Docker and orchestrated with Kubernetes or deployed as managed functions, and a CI/CD pipeline is set up so code moves from repository to production through automated, repeatable steps.\n\nHigh availability and monitoring are configured alongside the infrastructure rather than bolted on afterwards, and cost optimization is applied to the environment that actually ships. The sequence is the same whether the target is serverless, containerized, or a mix of both."
      },
      {
        "heading": "Which cloud technologies do you work with?",
        "body": "On AWS, our production cloud work includes AWS Lambda functions for serverless backends and cloud storage, as used on the Food Magnet: Vender platform. That project also runs a TablePlus database, Firebase for real-time data and notifications, OneSignal for push delivery, and Stripe for payments.\n\nFor containerized workloads we offer Docker for packaging and Kubernetes for orchestration, which keeps environments consistent across local, staging, and production. CI/CD pipeline setup automates build, test, and deploy so releases are reproducible rather than hand-run. These are services we offer; the serverless AWS work above is the example we can point to in production.\n\nOn the application side, the same project pairs a Flutter mobile app with a React.js admin dashboard, so the backend is designed around how the clients actually consume it. If your stack includes something we have not listed, we will tell you plainly whether it is a fit rather than force it into a template."
      },
      {
        "heading": "What does a serverless AWS backend look like in production?",
        "body": "Food Magnet: Vender is the clearest production example. Food truck vendors struggled with discoverability and real-time customer engagement, which is an infrastructure problem as much as a product one: locations change constantly and customers expect to see them update live.\n\nWe built a Flutter mobile app with a React admin dashboard and a serverless AWS backend supporting live location tracking. The architecture is component-based and serverless: AWS Lambda functions for backend logic, cloud storage, a TablePlus database, Firebase for real-time data and notifications, OneSignal for push, and Stripe for payments. It supports four user roles: admin, manager, vendor, and customer.\n\nThe result was increased vendor visibility and real-time food truck discovery for customers. The platform runs live on the web at foodmagnet.app and ships as Flutter apps on both the Google Play Store and the Apple App Store, which is the practical test of whether an architecture holds up outside a demo environment."
      },
      {
        "heading": "Can you modernize an existing application instead of rebuilding it?",
        "body": "Yes. Modernization starts by identifying what is genuinely slow, fragile, or expensive in the system you already run, rather than assuming the whole thing has to be replaced. An audit of hosting, deployment steps, and traffic patterns comes before any change.\n\nContainerizing an application with Docker, adding a CI/CD pipeline so deployments stop depending on one person, or moving a single heavy workload to managed or serverless components often removes the bottleneck without a full migration. Each of those is a self-contained change that can be tested and rolled back.\n\nThe same logic applies to availability and cost. Removing a single point of failure, adding monitoring so problems surface as signals rather than customer complaints, or right-sizing over-provisioned resources are all changes you can make to a live system incrementally.\n\nWe scope the smallest change that removes the bottleneck first, and you decide whether to go further from there."
      },
      {
        "heading": "How do you keep cloud costs and uptime under control?",
        "body": "High availability, monitoring, and cost optimization are treated as part of the architecture rather than extras added after launch. Availability comes from design decisions: removing single points of failure, using managed and serverless components where they reduce operational burden, and making sure a failed instance or function does not take the product down with it.\n\nMonitoring gives you visibility into what your systems are actually doing, so problems show up as signals from the infrastructure instead of complaints from users. That same visibility is what makes tuning possible.\n\nCost optimization follows from it. Serverless components such as AWS Lambda functions charge for what runs rather than for idle capacity, right-sizing removes over-provisioned resources, and storage and data transfer are reviewed for waste. Because the cost model and the architecture are the same set of decisions, your team can weigh spend against performance and redundancy as the product grows."
      }
    ],
    "deliverables": [
      "Provisioned AWS cloud infrastructure for your application, built as serverless functions, containers, or a mix of both",
      "AWS Lambda functions configured for backend logic where the workload suits serverless, as used on Food Magnet: Vender",
      "Docker packaging and Kubernetes orchestration for containerized workloads",
      "A configured CI/CD pipeline that moves code from repository to production through automated, repeatable steps",
      "High availability setup with single points of failure identified and addressed",
      "Monitoring configured for the deployed environment",
      "Cost optimization strategies applied to the running infrastructure, including right-sizing and serverless components in place of idle capacity"
    ],
    "faq": [
      {
        "q": "Do you work with applications that are already live, or only new builds?",
        "a": "Both. On a new build the architecture is designed alongside the application, as on Food Magnet: Vender, where a Flutter mobile app and React admin dashboard were built on a serverless AWS backend. A live application gets an assessment first, then targeted changes such as containerization, a CI/CD pipeline, or moving a heavy workload to managed services, so you are not forced into a full rewrite to fix one bottleneck."
      },
      {
        "q": "Should my backend be serverless or containerized?",
        "a": "It depends on the workload. Serverless on AWS Lambda functions fits event-driven products and charges only for what runs; that is the model behind Food Magnet: Vender. Docker and Kubernetes fit long-running processes and workloads that need fine-grained control over the runtime. We recommend one after reviewing your traffic patterns, data stores, and current deployment steps."
      },
      {
        "q": "Can you build the application layer as well as the infrastructure?",
        "a": "Yes. Food Magnet: Vender combines a Flutter mobile app, a React.js admin dashboard, and a serverless AWS backend with live location tracking, Firebase for real-time data and notifications, and Stripe for payments. It runs live at foodmagnet.app with listings on Google Play and the App Store, so the infrastructure and the clients that consume it were designed together."
      },
      {
        "q": "How do you keep the system running when part of it fails?",
        "a": "High availability is a design decision rather than an add-on. Single points of failure are identified and removed, managed and serverless components are used where they reduce operational burden, and monitoring is configured so problems show up as signals from the infrastructure instead of complaints from users."
      },
      {
        "q": "How do you approach cloud cost optimization?",
        "a": "Cost optimization starts with visibility. We review where resources are over-provisioned, where storage and data transfer are being wasted, and where serverless components such as AWS Lambda functions can replace idle capacity you pay for around the clock. Because cost and architecture are the same set of decisions, your team can weigh spend against performance and redundancy."
      }
    ],
    "word_count": 1103
  },
  "4": {
    "service_id": 4,
    "title": "Modern UI/UX Design Services | DevoraX",
    "meta_description": "UX research, user flows, design systems and accessible responsive interfaces, carried from Figma components through to production-ready front-end code.",
    "hero_answer": "Modern UI/UX is the design practice that turns a product idea into interfaces people can actually use: researched user flows, a reusable design system, responsive and accessible layouts, and motion that guides attention. DevoraX covers this service from Figma through to production-ready UI, so design decisions carry into the front-end code.",
    "sections": [
      {
        "heading": "Who is a modern UI/UX engagement for?",
        "body": "This service is for teams that know what they want to build and need the interface to match the ambition. That includes founders preparing a first release, product owners replacing a dated screen set, and companies whose workflows have outgrown the UI that was bolted on early.\n\nIt also fits products running across more than one surface. When the same brand has to hold together on a phone, a tablet and a wide desktop dashboard, a reusable system tends to be cheaper than another round of one-off pages.\n\nYou do not need an existing design team. This service covers five connected areas in one place: design systems and UI kits, UX research and user flows, responsive and accessible layouts, motion and micro-interactions, and the move from Figma to production-ready UI.\n\nThe work is most productive when there is a clear statement of what users must be able to accomplish, because that is what the flows get written against."
      },
      {
        "heading": "What does the UI/UX design process look like?",
        "body": "The work moves from understanding to structure to surface, in that order. Discovery maps what the product has to do, who is doing it and where the current experience breaks down, and that understanding is written up as user flows before anyone opens a visual design tool.\n\nStructure comes next. Flow diagrams and low-fidelity layouts settle navigation, hierarchy and edge cases while they are still cheap to change. That sequencing is the point: a disagreement about a flow is far less expensive to resolve on a diagram than on a finished screen.\n\nVisual design follows, built in Figma against a defined type scale, colour palette, spacing rhythm and component set rather than screen by screen. Motion and micro-interaction rules are decided at this stage too, so animation is a documented behaviour instead of an afterthought.\n\nThe last stage is production, where the design system becomes working, responsive front-end UI."
      },
      {
        "heading": "What is a design system and why does it matter?",
        "body": "A design system is a documented set of reusable interface parts: colour and type tokens, spacing rules, buttons, form fields, tables, navigation patterns, component states, and the rules for when each one is used. It is the difference between a set of attractive screens and a product that can grow without falling apart.\n\nThe practical benefit is that new screens get assembled from approved components instead of drawn from a blank canvas. The responsive and accessibility decisions already made inside those components carry forward rather than being re-argued each time a screen is added.\n\nIt also protects consistency. When several designers and developers touch a product over a long period, a system is what stops five slightly different buttons and three shades of the same blue from creeping in.\n\nDesign systems and UI kits are a defined part of this service, so designers and engineers work from one shared definition of the interface."
      },
      {
        "heading": "How do you research user flows before designing screens?",
        "body": "UX research and user flows are where this service starts, and the approach is practical rather than academic. It begins by defining the jobs each user type is trying to finish, then mapping the shortest credible path to each one, including the failure states projects often forget: empty data, partial permissions, slow connections and errors.\n\nThose paths become flow diagrams that name every screen, decision point and system response. They can be read without design vocabulary, which is why flows are a useful artefact for reaching agreement before visual work begins.\n\nWhere real users or existing analytics are available, both get used to challenge assumptions about what deserves screen space. Where they are not, the flows are tested against the product's own requirements and the assumptions behind them are written down so they can be revisited later.\n\nThe output is a flow map and an annotated screen inventory defining the scope of the design work."
      },
      {
        "heading": "Can you design data-heavy dashboards and analytics interfaces?",
        "body": "Yes, data-dense interfaces are within scope, and they are some of the harder interface work there is. Dense data raises problems marketing pages never face: many numbers competing for attention, values that change while the user is reading them, and the need to make a pattern legible at a glance.\n\nDevoraX built the Predictive Analytics Dashboard on the MERN stack. The problem was that businesses lacked real-time insights and predictive analytics to anticipate market trends and make data-driven decisions. The solution was a MERN-based analytics dashboard with real-time data pipelines and machine-learning models, and the result was real-time market insights, predictive analytics and faster strategic decision-making.\n\nThe design question a dense screen raises is always the same one. Decide what the user must notice first, give that element the strongest visual weight, and let supporting detail recede until it is asked for."
      },
      {
        "heading": "How do you make interfaces responsive and accessible?",
        "body": "Responsive and accessible layouts are one of the five parts of this service, and both are designed rather than retrofitted. Layouts are defined at the breakpoints the product actually needs, and components carry their own rules for how they reflow, so a data table on desktop can become a readable card stack on a phone instead of a horizontal scroll.\n\nAccessibility starts at the token level. Colour pairs are checked for contrast before they are chosen for taste, type sizes stay legible at real reading distances, and interactive targets are sized for thumbs rather than cursors.\n\nIn the components themselves, the work covers keyboard navigation, visible focus states, sensible heading structure and text alternatives for anything carrying meaning through image or colour alone.\n\nThose decisions are documented beside the components, so the rules that are load-bearing stay distinguishable from the ones that are merely stylistic."
      },
      {
        "heading": "How do Figma designs become production-ready UI?",
        "body": "A handoff fails when developers have to guess. The Figma file is therefore built the way the code will be structured: components with variants and states, named tokens for colour, type and spacing, and auto-layout so nothing depends on a designer's manual nudging.\n\nFrom there the system gets converted into real front-end components rather than one-off screen markup. Each component keeps its documented states, responsive behaviour and interaction rules, so the running interface matches the file instead of approximating it.\n\nMotion is specified the same way. Durations, easing and trigger conditions are written down as part of the component rather than improvised during development, which is what keeps micro-interactions consistent across a product.\n\nFigma to production-ready UI is a defined part of this service, which means the design system and the implemented interface are produced as two views of the same thing."
      }
    ],
    "deliverables": [
      "User flow diagrams covering each user type's primary path, including empty, error and permission states",
      "An annotated screen inventory that sets the scope of the design work",
      "A Figma design system: colour, type and spacing tokens plus a documented component library",
      "A UI kit of reusable components with their variants and states defined",
      "High-fidelity responsive screen designs at the breakpoints the product needs",
      "Motion and micro-interaction specifications covering duration, easing and trigger conditions",
      "Production-ready front-end UI components built from the design system",
      "Accessibility notes recorded beside each component: contrast pairings, focus states, keyboard paths and target sizes"
    ],
    "faq": [
      {
        "q": "What is included in the UI/UX service?",
        "a": "Five connected areas: design systems and UI kits, UX research and user flows, responsive and accessible layouts, motion and micro-interactions, and Figma to production-ready UI. Together they cover the path from understanding what users need to accomplish, through a documented component library, to an interface implemented as front-end code."
      },
      {
        "q": "Can you work with our existing brand instead of creating a new look?",
        "a": "Yes. Where brand colours, type and assets already exist, the design system can be built around them, documenting how they apply to interface states, contrast pairings and responsive layouts rather than replacing what you have."
      },
      {
        "q": "Do you only design, or does the service include front-end code?",
        "a": "Both are covered. Figma to production-ready UI is part of the service, so the design system can be implemented as working front-end components rather than stopping at static screens. Where the code is written matters less than keeping the components and the file consistent with each other."
      },
      {
        "q": "How are motion and micro-interactions handled?",
        "a": "They are treated as component behaviour rather than decoration added at the end. Duration, easing and trigger conditions are specified alongside the component they belong to, so the same interaction behaves the same way wherever it appears in the product."
      },
      {
        "q": "What information helps the work start well?",
        "a": "A clear statement of what users must be able to accomplish is the most useful input, because flows are written against it. Existing brand assets, and any analytics or access to real users you can share, help challenge assumptions early, though flows can also be tested against the product's own requirements."
      }
    ],
    "word_count": 1095
  }
};

export function getServiceContent(id: number | string): ServiceContent | undefined {
  return SERVICE_CONTENT[Number(id)];
}

/** When the long-form service copy above was last substantively rewritten. */
export const SERVICE_CONTENT_UPDATED = '2026-09-16T00:00:00.000Z';

/**
 * Curated case studies per service, by project id.
 *
 * The `service_id` column in Supabase is inverted against content depth: the only
 * projects it links to each service are 10-65 word stubs, while all ten long-form
 * case studies (1,260-1,556 words) have no service_id at all. So the strongest
 * proof each service page could show was reachable from nowhere on that page.
 *
 * Mapped here in code rather than by writing to production data: it is
 * reviewable in a diff and reversible. Assignments follow each project's real
 * stack, not marketing convenience.
 */
export const SERVICE_CASE_STUDIES: Record<number, number[]> = {
  // Mobile Innovation — React Native (Koor, Dooz) and Flutter (TAL, WOD) builds.
  1: [17, 25, 28, 31],
  // AI & Full-Stack Web — Next.js / React front ends on Supabase and Firebase.
  2: [32, 23, 24, 22],
  // Cloud Architecture — Node/AWS backends: microservices and media pipelines.
  3: [26, 30],
  // Modern UI/UX — the two most interface-led products in the record.
  4: [23, 22],
};
